feat: created gw file receiver service
MapColonies/gw-file-receiver pull request #2
Opened 2021-10-31 08:20 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-10-31 12:49 UTC, asafMasa requested changes
lint fails

2021-10-31 12:49 UTC, asafMasa commented on src/providers/storageProvider.ts
> +  //createWriteStream: (path: string) => Promise<Writable>;
remark?

2021-11-01 08:36 UTC, cl-shaharshavit-rnd commented on src/clients/syncManagerClient.ts
> +    super(logger, config.get('syncManagerUrl'), 'SyncManager', config.get('httpRetry'));
it is the name in the logs for the nifi service it isn't being used anywhere else and might be confusing in the global common constants

2021-11-01 13:51 UTC, asafMasa approved these changes

2021-11-02 08:53 UTC, yossiz16 approved these changes

2021-11-02 13:45 UTC, merged